### ISSUE TITLE
Sponsor Cards

### ISSUE THREAD

**Issue by danielgamage** [oakstudios/joinmastodon#11]
need to decide how this is handled between "gold", "silver", and "bronze" sponsors. we could have separate components for all three, but these two definitely share a lot visually:

![Image](https://user-images.githubusercontent.com/1642599/177828951-457ef1ee-61a8-4262-b775-78e043506fa6.png)

my best guess is keeping them all together since their data is so similar:
- props
  - [ ] `logo`
  - [ ] `name`
  - [ ] `url`/`link`
  - [ ] `tier` for `gold`, `silver`, and `bronze` as they're laid out [in figma](https://www.figma.com/file/Wk8L4YNZvgTBcrpthCYmBj/(internal-working)-wireframe?node-id=320%3A562), to switch between layouts

**Comment by mikabusante** [comment]
will start working on this today and also rendering these out on `/sponsors`
<img width="561" alt="Screen Shot 2022-07-26 at 8 40 33 AM" src="https://user-images.githubusercontent.com/31963784/181008186-10fd84a5-3e99-4da4-8742-8dfc99bfa6ac.png">
