### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by danielgamage** [oakstudios/joinmastodon#30]
arabic in particular should have some RTL accommodations in the design to have parity with the existing site as we dev our components out

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/1642599/179610404-b9801045-549d-4db4-bb67-847afac9293a.png">

we have some opportunities to fix some RTL bugs, too:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/1642599/179610333-2a49e2aa-5d08-4e8b-8b6c-114dc9288443.png">

there's [rtl selectors](https://tailwindcss.com/blog/tailwindcss-v3#rtl-and-ltr-modifiers) in tailwind which might occasionally be helpful (conditional illustrations), but compared to using logical properties for the layout, this approach would make RTL feel like an afterthought

[tailwindcss-logical](https://github.com/stevecochrane/tailwindcss-logical) seems better, giving us lower-level control of the properties used

compared to something like [tailwindcss-vanilla-rtl](https://github.com/thibaudcolas/tailwindcss-vanilla-rtl) which forces logical properties everywhere, having the ability to decide which design elements need to be re-aligned and where seems like a more appropriate and nuanced approach

opening this as an issue to keep this in mind and mark commits with it

**Comment by mikabusante** [comment]
anything left to do here?

**Comment by danielgamage** [comment]
from my limited understanding of how it should read, things are actually looking quite good

- [ ] https://joinmastodon.vercel.app/ar/sponsors is only rendering in english for some reason? does it need server-side localization props?

i thought about mirroring these icons (specifically feed), but i think since some of them represent physical objects or symbols (eg server rack, dollar sign), it would actually be very broken to flip all of them

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/1642599/182439854-4d23f5ab-8062-450b-9786-d9d441db81ee.png">

also thought about making these explicitly LTR, but since the FREE/PAID text is localized, i think RTL makes sense.

<img width="763" alt="Screen Shot 2022-08-02 at 13 40 19" src="https://user-images.githubusercontent.com/1642599/182439089-edbe21cc-7bb6-45fb-a2b0-03636764e23c.png">

**Comment by mikabusante** [comment]
> does it need server-side localization props? 

ur totatlly right, lemme push that rn

**Comment by mikabusante** [comment]
also i agree about keeping the icons as is!

**Comment by danielgamage** [comment]
cool we can close then 🏁
