### ISSUE TITLE
Load list of servers from API

### ISSUE THREAD

**Issue by mikabusante** [oakstudios/joinmastodon#36]
<img width="669" alt="Screen Shot 2022-07-20 at 11 28 08 AM" src="https://user-images.githubusercontent.com/31963784/180022149-ca36897f-5555-49a6-a49a-e81edbd0668b.png">

**Comment by mikabusante** [comment]
some questions about this:
1) Initially, will we show _all_ of the servers from all the different categories? (vs on v1, we only see 1 category at a time)
2) if so, will the featured servers section disappear after clicking a filter? i.e. we won't show the servers that are featured within a certain category
3) do we know how servers will be featured, maybe just a `featured: true` in the server data and we can filter from there? I guess this will be something new in the API

**Comment by danielgamage** [comment]
>do we know how servers will be featured, maybe just a featured: true in the server data and we can filter from there? I guess this will be something new in the API

this makes sense to me, but I'll ask about this in chat

cc @tyleemem on the other two Qs
