### ISSUE TITLE
Increase line height / font size on testimonial cards

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#47]
Could we increase the font size, or at least the line height of testimonials? They are very hard to read right now.

![](https://drp.mk/i/H6vpVrzj7Y.png)

Above:

1. Current (`b3`)
2. Increasing `b3`'s line height to 1.5 (matching `b2`)
3. Using `b2` instead of `b3`

**Comment by tyleemem** [comment]
yes to line height and newest 6

**Comment by mikabusante** [comment]
> I think testimonial text should be same size as "why mastodon" body text above. It's too small

back to a bigger text size!
