### ISSUE TITLE
Increase button font size

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#48]
Design:

![](https://drp.mk/i/y03Csy89S3.png)

Site:

![](https://drp.mk/i/0HvmXmDFwc.png)

(same goes for header CTA buttons)

**Comment by danielgamage** [comment]
rel https://www.figma.com/file/Wk8L4YNZvgTBcrpthCYmBj?node-id=320:1244#235296710

think this is fixed with the commits above. lmk if you see it elsewhere, though
