### ISSUE TITLE
Make homepage hero responsive

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#55]
I'm noticing some issues on smaller screens like my 13" MacBook:

![](https://drp.mk/i/ySwxSzfSWJ.png)

Most of the elephant is cut off.

Could we make this responsive instead of a static size?

Example:

https://user-images.githubusercontent.com/423740/181685019-c16a8fa9-07a1-4361-bc6c-4be14ee23d89.mp4

Changes required for this:

```
min-width: 200%; /* because image is almost 4000px but we only care about the middle 2000px on small screens */
max-width: 200%;
object-fit: contain;
left: -50%;
```

Also would help if:

- [ ] We put a background fill on the container, so the text is not white on white (in that case hero should have no transparency)
- [ ] The hero image has extra bleed on the top

Still works on larger screens too:

![](https://drp.mk/i/HYS5GTG8M9.png)

**Comment by danielgamage** [comment]
fwiw we were thinking of [using a extended-width version of the mobile hero on those smaller desktop sizes](https://www.figma.com/file/Wk8L4YNZvgTBcrpthCYmBj?node-id=1030:1760#237091089)
