### ISSUE TITLE
Dead space on Sponsors

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#61]
There is a lot of dead space "above the fold" on the Sponsors page /cc @tyleemem 

![](https://drp.mk/i/H45MxNWZ2V.png)

Is there a missing illustration?

![](https://drp.mk/i/yTGd43LLBv.png)

**Comment by mikabusante** [comment]
re the dead space, we can reduce the top padding on the section below, i can push that change rn!
<img width="1708" alt="Screen Shot 2022-08-02 at 8 51 38 AM" src="https://user-images.githubusercontent.com/31963784/182379096-4f0e1732-6797-4515-a2d2-bd62cb07b286.png">
