### ISSUE TITLE
Mouse users seeing scroll bars in collapsed menu (Safari)

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#65]
Getting these cute lil scroll bars in Safari:

![](https://drp.mk/i/0nfJCQ4pp6.png)

To repro, plug in an non-Apple mouse or turn on this setting:

![](https://drp.mk/i/1ssBy49Jxm.png)

**Comment by danielgamage** [comment]
should be fixed [on staging](https://joinmastodon.vercel.app/). tested on all desktop browsers with that setting, but lmk if you're still seeing
