### ISSUE TITLE
Delay when navigating to `/server`

### ISSUE THREAD

**Issue by mikabusante** [oakstudios/joinmastodon#66]
> There seems to be a delay when clicking "Servers" in the navbar before the page address updates and the new page opens. Made me think the link was not hooked up to anything at first.

I believe this is being caused by the API calls in `getServerSideProps`. idk if there is an easy way to cache the results so the API calls would only have to be made once and every request uses the same data? We could move it to a client side request?

**Comment by danielgamage** [comment]
there's [this](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#caching-with-server-side-rendering-ssr) but it doesn't seem to do much (at least locally, might be better on the server)

**Comment by mikabusante** [comment]
we could try it on the preview, apparently it is disabled in dev:
> Note: When running your application locally with next dev, your headers are overwritten to prevent caching locally.

https://nextjs.org/docs/going-to-production#caching

**Comment by danielgamage** [comment]
omg thanks for noticing that. i wish i knew how to read
