### ISSUE TITLE
Text/illo placement on `/apps`

### ISSUE THREAD

**Issue by mikabusante** [oakstudios/joinmastodon#67]
> I have to admit I feel weird about this gap on the apps page. I have to scroll down to see the download buttons. Meanwhile, right of "Apps" is empty too.

**Comment by mikabusante** [comment]
> Similar problem exists on the sponsors page, where I only see the top of the icons before scrolling down, giving the impression that the page is empty.
Some illustration with downward energy to fill the space might help in that instance

**Comment by mikabusante** [comment]
cc @tyleemem. re the sponsors page at least, we do have the pending illo so maybe that would help there? not sure what we can do about the apps page though

**Comment by Gargron** [comment]
The phone picture could move up to the right, and the download buttons could move up to the intersection between magenta and white.
