### ISSUE TITLE
Filter label styling + cursor changes

### ISSUE THREAD

**Issue by mikabusante** [oakstudios/joinmastodon#68]
> On the servers page, "Filters" looks like it could be a button, but it's just text. On the other hand, the languages dropdown looks like text - pointer cursor might help here
"Filter by language" has default cursor but is not a label that activates the dropdown

**Comment by mikabusante** [comment]
<img width="203" alt="Screen Shot 2022-08-09 at 1 11 50 PM" src="https://user-images.githubusercontent.com/31963784/183714585-3d0a102c-ecd4-4324-aa3f-b69d86d817d3.png">
i'm wondering if we should remove this label......I think it makes sense in the context of the full filter sidebar design where it has the groups of filters, but maybe it is confusing here??

**Comment by tyleemem** [comment]
yeah!
