### ISSUE TITLE
Navigation bug when visiting `/servers`

### ISSUE THREAD

**Issue by mikabusante** [oakstudios/joinmastodon#71]
> for some reason, going back to the homepage after being on the servers page, updates the page address but not the actual page, it stays on servers
Actually, I can't seem to be able to open any page after being on the servers page

**Comment by danielgamage** [comment]
can anyone else repro this?

**Comment by mikabusante** [comment]
I can repro after clicking the repo link:

1. from the home page click "Code"
2. hit the back button
3. Now i'm stuck on the homepage, clicking other nav items updates the url but not the page :0

**Comment by mikabusante** [comment]
actually, just went back to this, and the above no longer repros the issue hmmmm

**Comment by danielgamage** [comment]
so i can still repro it, but only in firefox? (v103)

**Comment by mikabusante** [comment]
i'm also trying to repro in firefox v103, but no luck for me

**Comment by danielgamage** [comment]
fwiw it only happens when i:

1. **open a *new* tab**
1. **go to [staging](https://joinmastodon.vercel.app/)** (local is fine?)

then the steps you listed:

3. from the home page click "Code"
1. hit the back button
1. Now i'm stuck on the homepage, clicking other nav items updates the url but not the page :0

but it seems like more JS is broken than just the router, eg the header BG won't update:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1642599/183124369-a90668c8-7d3f-4e0c-90e0-5f2f59d1a8f8.png">

**Comment by mikabusante** [comment]
ty ty, i can repro with that. there are these errors in the console:
<img width="873" alt="Screen Shot 2022-08-05 at 1 04 29 PM" src="https://user-images.githubusercontent.com/31963784/183126311-b14771e5-d043-4e82-a98e-88bf333bd398.png">

are you seeing these too? maybe something with loading the locale data?? 🔍

**Comment by danielgamage** [comment]
lol i'm glad you found that bc mine has 0 errors! 😰

**Comment by mikabusante** [comment]
maybe related https://github.com/i18next/next-i18next/issues/988?

**Comment by mikabusante** [comment]
also, i can repro locally when running `yarn build`/`yarn start`, just making sure it wasn't a vercel related issue

**Comment by mikabusante** [comment]
ok -- I believe this is a nextjs issue, but I don't fully understand it. I'd guess that this function runs when returning from an external page. That second return statement (`return e`) is not getting tree-shaken out and that's causing issues?
<img width="590" alt="Screen Shot 2022-08-05 at 1 46 35 PM" src="https://user-images.githubusercontent.com/31963784/183132432-adb7f401-d709-4b38-be34-f1d3bf7fb944.png">

a fix we can do on our side is having external links open in a new tab?

**Comment by danielgamage** [comment]
i was wondering about the link thing too. 1571742e66 ([preview](https://joinmastodon-hc8o6tsf3-oakstudios.vercel.app/)) didn't help, but maybe using plain `a` tags would work
