### ISSUE TITLE
Testimonial bugs + carousel?

### ISSUE THREAD

**Issue by mikabusante** [oakstudios/joinmastodon#72]
> I can barely see rounded corners on testimonial avatars. It was also supposed to be a carousel originally, right?

We can increase the border radius to 4px (I think it's 2px right now). Also if we're going back to the carousel, could check out https://keen-slider.io/

**Comment by mikabusante** [comment]
![unknown](https://user-images.githubusercontent.com/31963784/182919514-7adf73ed-1393-44ff-b9d7-280f6ee3a448.png)
also this, but doesn't need to be fixed if we go with the carousel.

**Comment by mikabusante** [comment]
ok -- trying to add the carousel on [this branch](https://github.com/oakstudios/joinmastodon/tree/carousel-%2372) with keen slider but it's pretty unstable :///

looks great with ltr languages but breaks entirely when switching to rtl. 

https://user-images.githubusercontent.com/31963784/183095029-588deabc-b51d-4ac4-afd0-ea6bd5fa67ce.mp4

the slider has a `rtl: true || false` option but I can't seem to get it to work with either direction, so we couldn't even just keep it on LTR mode, it breaks either way. 

Looks fine after a refresh, but since the locale change does not refresh the page, this isn't going to work.

**Comment by mikabusante** [comment]
@danielgamage do u have any ideas for this? This uses `keen-slider`, but last week with no success I also tried :
- flickity-react-component
- vanilla flickity
- pure-react-carousel
- slick

unless there's an option I haven't tried yet, can we just straight up nix the carousel since I can't seem to find a good solution that a) isn't huge, b) is stable, c) functions well.

**Comment by Gargron** [comment]
The carousel can go left to right on RTL languages too. I think the surrounding element just needs `dir: ltr` on it to make sure it stays the same way when whole page direction is changed.

**Comment by mikabusante** [comment]
ok good to know, I'll try that 👍
