### ISSUE TITLE
Basic pages need a little love

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#85]
Contact, Privacy, etc are looking very rough. Font is very tiny and text is being cut off by footer:

![](https://drp.mk/i/36S6gJgBL.png)

https://joinmastodon.org/privacy-policy

Can we give these pages more love?

**Comment by danielgamage** [comment]
confirming: your browser is about twice the width of the screenshot, right?

these should probably use the `b1` type style, but it looks like it isn't applied anywhere in the html tree. i can add it to the root of this layout
