### ISSUE TITLE
Update b&w logos on brand page

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#91]
- [x] Remove old b&w wordmark options:

![image](https://user-images.githubusercontent.com/423740/191061091-9f552e61-9e35-4946-92db-56c22ab7ead7.png)

- [x] Replace with these options ([drive](https://drive.google.com/open?id=1puiR_HQBdexVMVkk-yzqGNO8b-ZrBxvr&authuser=tylee%40oak.is&usp=drive_fs)):

![image](https://user-images.githubusercontent.com/423740/191061266-1dfa3db8-ec8f-40b6-8c71-411b22dfbe6c.png)

- [x] Add note to use `m` workmark in cases where only 1 color is possible (e.g. screenprinting, faxes, etc)

**Comment by danielgamage** [comment]
looks done via mastodon/joinmastodon/pull/217
